//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiadMV.Manager.Resources.MessagesResources", typeof(MessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delivery group does not exist..
        /// </summary>
        public static string ErrorDeliveryGroupNotExist {
            get {
                return ResourceManager.GetString("ErrorDeliveryGroupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Delivery with the informed Postmates Delivery Id was not found..
        /// </summary>
        public static string ErrorDeliveryNotExistDescription {
            get {
                return ResourceManager.GetString("ErrorDeliveryNotExistDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Delivery does not exist..
        /// </summary>
        public static string ErrorDeliveryNotExistTitle {
            get {
                return ResourceManager.GetString("ErrorDeliveryNotExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Deliveries already exist for selected year and group. Use Update command instead..
        /// </summary>
        public static string ErrorDeliveryScheduleAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorDeliveryScheduleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected API Resource is not valid..
        /// </summary>
        public static string ErrorExternalServiceInvalidApiResourceDescription {
            get {
                return ResourceManager.GetString("ErrorExternalServiceInvalidApiResourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid API Resource..
        /// </summary>
        public static string ErrorExternalServiceInvalidApiResourceTitle {
            get {
                return ResourceManager.GetString("ErrorExternalServiceInvalidApiResourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request type is not valid..
        /// </summary>
        public static string ErrorExternalServiceInvalidRequestTypeDescription {
            get {
                return ResourceManager.GetString("ErrorExternalServiceInvalidRequestTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request.
        /// </summary>
        public static string ErrorExternalServiceInvalidRequestTypeTitle {
            get {
                return ResourceManager.GetString("ErrorExternalServiceInvalidRequestTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no response from the requested URL..
        /// </summary>
        public static string ErrorExternalServiceUnavailableDescription {
            get {
                return ResourceManager.GetString("ErrorExternalServiceUnavailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Unavailable.
        /// </summary>
        public static string ErrorExternalServiceUnavailableTitle {
            get {
                return ResourceManager.GetString("ErrorExternalServiceUnavailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has only one address. .
        /// </summary>
        public static string ErrorLastUserAddress {
            get {
                return ResourceManager.GetString("ErrorLastUserAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has only one provider..
        /// </summary>
        public static string ErrorLastUserProvider {
            get {
                return ResourceManager.GetString("ErrorLastUserProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no active subscription for current user..
        /// </summary>
        public static string ErrorNoActiveSubscriptionForUser {
            get {
                return ResourceManager.GetString("ErrorNoActiveSubscriptionForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order does not exist..
        /// </summary>
        public static string ErrorOrderNotExist {
            get {
                return ResourceManager.GetString("ErrorOrderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The person already exists..
        /// </summary>
        public static string ErrorPersonAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorPersonAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The person already has an active subscription for this address and this product category..
        /// </summary>
        public static string ErrorPreviousSubscriptionExists {
            get {
                return ResourceManager.GetString("ErrorPreviousSubscriptionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product does not exist..
        /// </summary>
        public static string ErrorProductNotExist {
            get {
                return ResourceManager.GetString("ErrorProductNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription is cancelled and can&apos;t be modified..
        /// </summary>
        public static string ErrorSubscriptionAlreadyCancelled {
            get {
                return ResourceManager.GetString("ErrorSubscriptionAlreadyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription does not exist..
        /// </summary>
        public static string ErrorSubscriptionNotExist {
            get {
                return ResourceManager.GetString("ErrorSubscriptionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription plan does not exist..
        /// </summary>
        public static string ErrorSubscriptionPlanNotExist {
            get {
                return ResourceManager.GetString("ErrorSubscriptionPlanNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address does not exist..
        /// </summary>
        public static string ErrorUserAddressNotExists {
            get {
                return ResourceManager.GetString("ErrorUserAddressNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user already exists..
        /// </summary>
        public static string ErrorUserAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorUserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not exist..
        /// </summary>
        public static string ErrorUserNotExist {
            get {
                return ResourceManager.GetString("ErrorUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider does not exist..
        /// </summary>
        public static string ErrorUserProviderNotExist {
            get {
                return ResourceManager.GetString("ErrorUserProviderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter could not be parsed..
        /// </summary>
        public static string ErrorWrongParameterDescription {
            get {
                return ResourceManager.GetString("ErrorWrongParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong configuration parameter.
        /// </summary>
        public static string ErrorWrongParameterTitle {
            get {
                return ResourceManager.GetString("ErrorWrongParameterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ZipCode does not exist..
        /// </summary>
        public static string ErrorZipCodeNotExist {
            get {
                return ResourceManager.GetString("ErrorZipCodeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} was cancelled!.
        /// </summary>
        public static string OrderCancelledNotificationDescription {
            get {
                return ResourceManager.GetString("OrderCancelledNotificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order cancelled!.
        /// </summary>
        public static string OrderCancelledNotificationTitle {
            get {
                return ResourceManager.GetString("OrderCancelledNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} created!.
        /// </summary>
        public static string OrderCreatedNotificationDescription {
            get {
                return ResourceManager.GetString("OrderCreatedNotificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order Received!.
        /// </summary>
        public static string OrderCreatedNotificationTitle {
            get {
                return ResourceManager.GetString("OrderCreatedNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0} was updated!.
        /// </summary>
        public static string OrderUpdatedNotificationDescription {
            get {
                return ResourceManager.GetString("OrderUpdatedNotificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Updated!.
        /// </summary>
        public static string OrderUpdatedNotificationTitle {
            get {
                return ResourceManager.GetString("OrderUpdatedNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact web page: {0}.
        /// </summary>
        public static string SendContactFormSubject {
            get {
                return ResourceManager.GetString("SendContactFormSubject", resourceCulture);
            }
        }
    }
}
