//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiadMV.Manager.Resources.MessagesResources", typeof(MessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Common Expression does not exist..
        /// </summary>
        public static string ErrorCommonExpressionNotExist {
            get {
                return ResourceManager.GetString("ErrorCommonExpressionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected API Resource is not valid..
        /// </summary>
        public static string ErrorExternalServiceInvalidApiResourceDescription {
            get {
                return ResourceManager.GetString("ErrorExternalServiceInvalidApiResourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid API Resource..
        /// </summary>
        public static string ErrorExternalServiceInvalidApiResourceTitle {
            get {
                return ResourceManager.GetString("ErrorExternalServiceInvalidApiResourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request type is not valid..
        /// </summary>
        public static string ErrorExternalServiceInvalidRequestTypeDescription {
            get {
                return ResourceManager.GetString("ErrorExternalServiceInvalidRequestTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request.
        /// </summary>
        public static string ErrorExternalServiceInvalidRequestTypeTitle {
            get {
                return ResourceManager.GetString("ErrorExternalServiceInvalidRequestTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no response from the requested URL..
        /// </summary>
        public static string ErrorExternalServiceUnavailableDescription {
            get {
                return ResourceManager.GetString("ErrorExternalServiceUnavailableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Unavailable.
        /// </summary>
        public static string ErrorExternalServiceUnavailableTitle {
            get {
                return ResourceManager.GetString("ErrorExternalServiceUnavailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Key Fact does not exist..
        /// </summary>
        public static string ErrorKeyFactNotExist {
            get {
                return ResourceManager.GetString("ErrorKeyFactNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has only one address..
        /// </summary>
        public static string ErrorLastUserAddress {
            get {
                return ResourceManager.GetString("ErrorLastUserAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has only one provider..
        /// </summary>
        public static string ErrorLastUserProvider {
            get {
                return ResourceManager.GetString("ErrorLastUserProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Question does not exist..
        /// </summary>
        public static string ErrorQuestionNotExist {
            get {
                return ResourceManager.GetString("ErrorQuestionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address does not exist..
        /// </summary>
        public static string ErrorUserAddressNotExists {
            get {
                return ResourceManager.GetString("ErrorUserAddressNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user already exists..
        /// </summary>
        public static string ErrorUserAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorUserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Case does not exist..
        /// </summary>
        public static string ErrorUserCaseNotExist {
            get {
                return ResourceManager.GetString("ErrorUserCaseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not exist..
        /// </summary>
        public static string ErrorUserNotExist {
            get {
                return ResourceManager.GetString("ErrorUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider does not exist..
        /// </summary>
        public static string ErrorUserProviderNotExist {
            get {
                return ResourceManager.GetString("ErrorUserProviderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter could not be parsed..
        /// </summary>
        public static string ErrorWrongParameterDescription {
            get {
                return ResourceManager.GetString("ErrorWrongParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong configuration parameter.
        /// </summary>
        public static string ErrorWrongParameterTitle {
            get {
                return ResourceManager.GetString("ErrorWrongParameterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a example message.
        /// </summary>
        public static string ExampleMessage {
            get {
                return ResourceManager.GetString("ExampleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This example message can show two inputs. First: {0}, and Second {1}.
        /// </summary>
        public static string ExampleMessageWithContent {
            get {
                return ResourceManager.GetString("ExampleMessageWithContent", resourceCulture);
            }
        }
    }
}
