//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiadMV.API.Resources.MessagesResources", typeof(MessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must inform Delivery Groups..
        /// </summary>
        public static string DeliveryGroupsNotInformed {
            get {
                return ResourceManager.GetString("DeliveryGroupsNotInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Delivery Type is no available for selected Zip Code..
        /// </summary>
        public static string DeliveryTypeNoAvailableForCurrentZip {
            get {
                return ResourceManager.GetString("DeliveryTypeNoAvailableForCurrentZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested delivery type is not available por current zip..
        /// </summary>
        public static string DeliveryTypeNotAvailableForCurrentZip {
            get {
                return ResourceManager.GetString("DeliveryTypeNotAvailableForCurrentZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Delivery Update was registered succesfully..
        /// </summary>
        public static string DeliveryUpdateSuccess {
            get {
                return ResourceManager.GetString("DeliveryUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cart does not exist..
        /// </summary>
        public static string ErrorCartNotExists {
            get {
                return ResourceManager.GetString("ErrorCartNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Open Stores..
        /// </summary>
        public static string ErrorNoOpenStores {
            get {
                return ResourceManager.GetString("ErrorNoOpenStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no open stores on {0}..
        /// </summary>
        public static string ErrorNoOpenStoresDetails {
            get {
                return ResourceManager.GetString("ErrorNoOpenStoresDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Store is not Open..
        /// </summary>
        public static string ErrorStoreIsNotOpen {
            get {
                return ResourceManager.GetString("ErrorStoreIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Store with id &apos;{0}&apos; is not open on &apos;{1}&apos;..
        /// </summary>
        public static string ErrorStoreIsNotOpenDetails {
            get {
                return ResourceManager.GetString("ErrorStoreIsNotOpenDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Store does not exist..
        /// </summary>
        public static string ErrorStoreNotExists {
            get {
                return ResourceManager.GetString("ErrorStoreNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Store with id &apos;{0}&apos; does not exist..
        /// </summary>
        public static string ErrorStoreNotExistsDetails {
            get {
                return ResourceManager.GetString("ErrorStoreNotExistsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address does not exist..
        /// </summary>
        public static string ErrorUserAddressNotExists {
            get {
                return ResourceManager.GetString("ErrorUserAddressNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not exist..
        /// </summary>
        public static string ErrorUserNotExists {
            get {
                return ResourceManager.GetString("ErrorUserNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Provider does not exist..
        /// </summary>
        public static string ErrorUserProviderNotExists {
            get {
                return ResourceManager.GetString("ErrorUserProviderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address was removed from the application successfully..
        /// </summary>
        public static string InformationRemoveAddressSuccess {
            get {
                return ResourceManager.GetString("InformationRemoveAddressSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Provider was removed from the user..
        /// </summary>
        public static string InformationRemoveUserProvider {
            get {
                return ResourceManager.GetString("InformationRemoveUserProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with email &apos;{1}&apos; was removed from the application successfully..
        /// </summary>
        public static string InformationRemoveUserSuccess {
            get {
                return ResourceManager.GetString("InformationRemoveUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Zip Code does not have delivery types registered..
        /// </summary>
        public static string NoDeliveryTypesFoundForCurrentZip {
            get {
                return ResourceManager.GetString("NoDeliveryTypesFoundForCurrentZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subscriptions found for user with id {0}..
        /// </summary>
        public static string NoSubscriptionsFoundForUser {
            get {
                return ResourceManager.GetString("NoSubscriptionsFoundForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subscription plans found..
        /// </summary>
        public static string NoSubscriptionsPlansFound {
            get {
                return ResourceManager.GetString("NoSubscriptionsPlansFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order does not exist..
        /// </summary>
        public static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product does not exist..
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scheduled deliveries were found..
        /// </summary>
        public static string ScheduledDeliveryNotFound {
            get {
                return ResourceManager.GetString("ScheduledDeliveryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Zip Code was not found on database..
        /// </summary>
        public static string ZipCodeNotFound {
            get {
                return ResourceManager.GetString("ZipCodeNotFound", resourceCulture);
            }
        }
    }
}
