//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiadMV.API.Resources.MessagesResources", typeof(MessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Common Expression does not exist..
        /// </summary>
        public static string ErrorCommonExpressionNotExists {
            get {
                return ResourceManager.GetString("ErrorCommonExpressionNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Key Fact does not exist..
        /// </summary>
        public static string ErrorKeyFactNotExists {
            get {
                return ResourceManager.GetString("ErrorKeyFactNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Question does not exist..
        /// </summary>
        public static string ErrorQuestionNotExists {
            get {
                return ResourceManager.GetString("ErrorQuestionNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Address does not exist..
        /// </summary>
        public static string ErrorUserAddressNotExists {
            get {
                return ResourceManager.GetString("ErrorUserAddressNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The User Case dose not exist..
        /// </summary>
        public static string ErrorUserCaseNotExists {
            get {
                return ResourceManager.GetString("ErrorUserCaseNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user does not exist..
        /// </summary>
        public static string ErrorUserNotExists {
            get {
                return ResourceManager.GetString("ErrorUserNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Provider does not exist..
        /// </summary>
        public static string ErrorUserProviderNotExists {
            get {
                return ResourceManager.GetString("ErrorUserProviderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Address was removed from the application successfully..
        /// </summary>
        public static string InformationRemoveAddressSuccess {
            get {
                return ResourceManager.GetString("InformationRemoveAddressSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Provider was removed from the user..
        /// </summary>
        public static string InformationRemoveUserProvider {
            get {
                return ResourceManager.GetString("InformationRemoveUserProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} with email &apos;{1}&apos; was removed from the application successfully..
        /// </summary>
        public static string InformationRemoveUserSuccess {
            get {
                return ResourceManager.GetString("InformationRemoveUserSuccess", resourceCulture);
            }
        }
    }
}
